cluster.name: linuxfr_org

path.data: db/elasticsearch
path.logs: log

# disable cluster discovery
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: []

# disable index sharding and replication
index.number_of_shards: 1
index.number_of_replicas: 0
